Assuming unrestricted shared filesystem usage.
None
host: MacBook-Pro-de-Grigoryan.local
Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Submitting maximum 100 job(s) over 1.0 second(s).
Using shell: /bin/bash
Provided cores: 11
Rules claiming more threads will be scaled down.
Job stats:
job                     count
--------------------  -------
compute_negcon_stats        1
total                       1

Resources before job selection: {'_cores': 11, '_nodes': 9223372036854775807, '_job_count': 9223372036854775807}
Ready jobs: 1
Select jobs to execute...
Selecting jobs to run using greedy solver.
Selected jobs: 1
Resources after job selection: {'_cores': 10, '_nodes': 9223372036854775806, '_job_count': 100}
Execute 1 jobs...
[Thu Apr  3 10:46:19 2025]
localrule compute_negcon_stats:
    input: /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/CP_data/raw.parquet
    output: outputs/profiles/neg_stats.parquet
    jobid: 0
    reason: Forced execution
    resources: tmpdir=/var/folders/s6/prvmffjx7bl2mwcbcpxy05ph0000gn/T
Shell command: None
General args: ['--force', '--target-files-omit-workdir-adjustment', '', '--max-inventory-time 0', '--nocolor', '--notemp', '--no-hooks', '--nolock', '--ignore-incomplete', '', '--verbose ', '--rerun-triggers software-env mtime params input code', '', '', '', '', "--conda-frontend 'conda'", '', '', '', '', '', '--shared-fs-usage input-output sources source-cache software-deployment persistence storage-local-copies', '', "--wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/'", '', '', '', '--printshellcmds ', '', '--latency-wait 5', "--scheduler 'ilp'", '', '--local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl', "--scheduler-solver-path '/opt/anaconda3/bin'", '', '', '', '', '', '', '--default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI=']
spawned job: cd /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake && /opt/anaconda3/bin/python3.12 -m snakemake --snakefile '/Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake/Snakefile' --target-jobs 'compute_negcon_stats:' --allowed-rules compute_negcon_stats --cores 11 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --verbose  --rerun-triggers software-env mtime params input code --conda-frontend 'conda' --shared-fs-usage input-output sources source-cache software-deployment persistence storage-local-copies --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --printshellcmds  --latency-wait 5 --scheduler 'ilp' --local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl --scheduler-solver-path '/opt/anaconda3/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'
Waiting for more resources.
Full Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake && /opt/anaconda3/bin/python3.12 -m snakemake --snakefile '/Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake/Snakefile' --target-jobs 'compute_negcon_stats:' --allowed-rules compute_negcon_stats --cores 11 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --verbose  --rerun-triggers software-env mtime params input code --conda-frontend 'conda' --shared-fs-usage input-output sources source-cache software-deployment persistence storage-local-copies --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --printshellcmds  --latency-wait 5 --scheduler 'ilp' --local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl --scheduler-solver-path '/opt/anaconda3/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()
snakemake.exceptions.SpawnedJobError

Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake && /opt/anaconda3/bin/python3.12 -m snakemake --snakefile '/Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake/Snakefile' --target-jobs 'compute_negcon_stats:' --allowed-rules compute_negcon_stats --cores 11 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --verbose  --rerun-triggers software-env mtime params input code --conda-frontend 'conda' --shared-fs-usage input-output sources source-cache software-deployment persistence storage-local-copies --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --printshellcmds  --latency-wait 5 --scheduler 'ilp' --local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl --scheduler-solver-path '/opt/anaconda3/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Thu Apr  3 10:46:21 2025]
Error in rule compute_negcon_stats:
    message: None
    jobid: 0
    input: /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/CP_data/raw.parquet
    output: outputs/profiles/neg_stats.parquet
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Thu Apr  3 10:46:21 2025]
Error in rule compute_negcon_stats:
    message: None
    jobid: 0
    input: /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/CP_data/raw.parquet
    output: outputs/profiles/neg_stats.parquet
Complete log(s): /Users/grigoryanmariam/newproject/2025_Grigoryan_Proteomics/00.exploratory_analysis/snakemake/.snakemake/log/2025-04-03T104619.054145.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/cli.py", line 2172, in args_to_api
    dag_api.execute_workflow(
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/api.py", line 606, in execute_workflow
    workflow.execute(
  File "/opt/anaconda3/lib/python3.12/site-packages/snakemake/workflow.py", line 1428, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
